<a href="https://colab.research.google.com/github/LLLLCCJ/codebu/blob/master/pytorch_firstin_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

torch.__version__

'1.11.0+cu113'

In [3]:
x=torch.empty(4,2)

In [4]:
x

tensor([[1.0901e-34, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30]])

In [5]:
x=torch.rand(4,2)

In [6]:
x

tensor([[0.3720, 0.7700],
        [0.3324, 0.4954],
        [0.9564, 0.3868],
        [0.2624, 0.3410]])

In [7]:
x=torch.zeros(4,2,dtype=torch.long)

In [8]:
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [9]:
x=torch.tensor([3,2.3])

In [10]:
x

tensor([3.0000, 2.3000])

In [11]:
x=x.new_ones(2,4,dtype=torch.double)

In [12]:
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [13]:
x=torch.randn_like(x,dtype=torch.float)

In [14]:
x

tensor([[ 0.6985, -0.2009, -0.2430, -0.9190],
        [-0.8151,  0.0975, -0.2498,  0.5547]])

In [15]:
print(x.size())

torch.Size([2, 4])


In [16]:
ft=torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [17]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [18]:
it=torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [19]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


In [20]:
x=torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([1.1429])
1.1429414749145508
torch.float32


In [21]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y=torch.ones_like(x,device=device)
print(y)
x=x.to(device)
print(x)
z=x+y
print(z)
print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([1.1429], device='cuda:0')
tensor([2.1429], device='cuda:0')
tensor([2.1429], dtype=torch.float64)


In [22]:
t0=torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [24]:
t1=torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [26]:
t2=torch.tensor([[1,2,3],
                 [2,3,4]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [2, 3, 4]])
