In [1]:
import torch

torch.__version__

'1.11.0+cu113'

In [2]:
x=torch.empty(4,2)

In [3]:
x

tensor([[4.5519e-35, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30]])

In [4]:
x=torch.rand(4,2)

In [5]:
x

tensor([[0.3479, 0.9148],
        [0.9029, 0.7721],
        [0.1920, 0.4351],
        [0.4523, 0.5412]])

In [6]:
x=torch.zeros(4,2,dtype=torch.long)

In [7]:
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [8]:
x=torch.tensor([3,2.3])

In [9]:
x

tensor([3.0000, 2.3000])

In [10]:
x=x.new_ones(2,4,dtype=torch.double)

In [11]:
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [12]:
x=torch.randn_like(x,dtype=torch.float)

In [13]:
x

tensor([[-0.0177,  0.7404, -2.0710,  0.6672],
        [-0.9638, -1.6724, -0.6568, -1.2331]])

In [14]:
print(x.size())

torch.Size([2, 4])


In [15]:
ft=torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [16]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [17]:
it=torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [18]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


In [19]:
x=torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.6752])
0.675210177898407
torch.float32


In [20]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y=torch.ones_like(x,device=device)
print(y)
x=x.to(device)
print(x)
z=x+y
print(z)
print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([0.6752], device='cuda:0')
tensor([1.6752], device='cuda:0')
tensor([1.6752], dtype=torch.float64)


In [21]:
t0=torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [22]:
t1=torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [23]:
t2=torch.tensor([[1,2,3],
                 [2,3,4]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [2, 3, 4]])


In [24]:
t3=torch.tensor([[[1,2,3],
                  [2,4,6]],
                 [[6,7,8],
                 [9,8,7]]])
print(t3.ndim)
print(t3.shape)
print(t3)



3
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [2, 4, 6]],

        [[6, 7, 8],
         [9, 8, 7]]])


In [25]:
import math

a=torch.rand(1,2)*2-1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a,-0.5,0.5))

tensor([[0.7094, 0.9148]])
tensor([[0.7094, 0.9148]])
tensor([[1., 1.]])
tensor([[0., 0.]])
tensor([[0.5000, 0.5000]])


In [26]:
x=torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.9604, 0.1083],
        [0.2863, 0.6031]])
torch.return_types.max(
values=tensor([0.9604, 0.6031]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([0.9604, 0.6031]),
indices=tensor([0, 1]))


In [27]:
print(x)
print(x.min(dim=0))
print(x.max(dim=1))

tensor([[0.9604, 0.1083],
        [0.2863, 0.6031]])
torch.return_types.min(
values=tensor([0.2863, 0.1083]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([0.9604, 0.6031]),
indices=tensor([0, 1]))


In [28]:
x=torch.rand(2,2)
print(x)
y=torch.rand(2,2)
print(y)

tensor([[0.3432, 0.8746],
        [0.1207, 0.5251]])
tensor([[0.9053, 0.4763],
        [0.8506, 0.6155]])


In [29]:
print(x+y)
print(torch.add(x,y))

tensor([[1.2485, 1.3508],
        [0.9713, 1.1406]])
tensor([[1.2485, 1.3508],
        [0.9713, 1.1406]])


In [30]:
import warnings
warnings.filterwarnings('ignore')

In [31]:
result=torch.empty(2,4)
torch.add(x,y,out=result)
print(result)

tensor([[1.2485, 1.3508],
        [0.9713, 1.1406]])


In [32]:
print(x)
print(y)
y.add(x)
print(y)

tensor([[0.3432, 0.8746],
        [0.1207, 0.5251]])
tensor([[0.9053, 0.4763],
        [0.8506, 0.6155]])
tensor([[0.9053, 0.4763],
        [0.8506, 0.6155]])


In [33]:
print(x)
print(y)
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[0.3432, 0.8746],
        [0.1207, 0.5251]])
tensor([[0.9053, 0.4763],
        [0.8506, 0.6155]])
tensor([[-0.5621,  0.3983],
        [-0.7300, -0.0904]])
tensor([[-0.5621,  0.3983],
        [-0.7300, -0.0904]])
tensor([[-0.5621,  0.3983],
        [-0.7300, -0.0904]])


In [34]:
print(x)
print(y)
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[0.3432, 0.8746],
        [0.1207, 0.5251]])
tensor([[0.9053, 0.4763],
        [0.8506, 0.6155]])
tensor([[0.3107, 0.4165],
        [0.1026, 0.3232]])
tensor([[0.3107, 0.4165],
        [0.1026, 0.3232]])
tensor([[0.3107, 0.4165],
        [0.1026, 0.3232]])


In [37]:
print(x)
print(y)
print(torch.matmul(x,y))
z=torch.mm(x,y)
print(z)

tensor([[0.3432, 0.8746],
        [0.1207, 0.5251]])
tensor([[0.9053, 0.4763],
        [0.8506, 0.6155]])
tensor([[1.0546, 0.7018],
        [0.5559, 0.3807]])
tensor([[1.0546, 0.7018],
        [0.5559, 0.3807]])


In [38]:
print(torch.svd(z))

torch.return_types.svd(
U=tensor([[-0.8829, -0.4695],
        [-0.4695,  0.8829]]),
S=tensor([1.4348, 0.0079]),
V=tensor([[-0.8309, -0.5564],
        [-0.5564,  0.8309]]))


In [39]:
x=torch.Tensor([[1,2],
                [3,4]])
print(x)
print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

print(x[:,0])
print(x[:,1])

print(x[0,:])
print(x[1,:])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


In [40]:
x=torch.randn(4,5)
print(x)
y=x.view(20)
print(y)
z=x.view(5,-1)
print(z)

tensor([[ 0.4544,  1.9174, -0.4294,  0.6901, -0.0026],
        [ 0.5729,  0.2702,  1.4547, -1.1081, -0.2569],
        [-1.2885,  0.1647, -0.0843,  2.4405,  1.0027],
        [-1.1808,  0.6696,  0.0355, -0.9674, -0.1937]])
tensor([ 0.4544,  1.9174, -0.4294,  0.6901, -0.0026,  0.5729,  0.2702,  1.4547,
        -1.1081, -0.2569, -1.2885,  0.1647, -0.0843,  2.4405,  1.0027, -1.1808,
         0.6696,  0.0355, -0.9674, -0.1937])
tensor([[ 0.4544,  1.9174, -0.4294,  0.6901],
        [-0.0026,  0.5729,  0.2702,  1.4547],
        [-1.1081, -0.2569, -1.2885,  0.1647],
        [-0.0843,  2.4405,  1.0027, -1.1808],
        [ 0.6696,  0.0355, -0.9674, -0.1937]])


In [42]:
x=torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.7075])
-0.7075012922286987
torch.float32


In [43]:
x=torch.randn(2)
print(x)
print(x.item())
print(x.dtype)

tensor([-1.5394,  0.3877])


ValueError: ignored

In [44]:
tensor=torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.4915, 0.2598, 0.7575],
         [0.8342, 0.9627, 0.7448],
         [0.0259, 0.6993, 0.5997]]])
torch.Size([1, 3, 3])


In [45]:
t=tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.4915, 0.2598, 0.7575],
        [0.8342, 0.9627, 0.7448],
        [0.0259, 0.6993, 0.5997]])
torch.Size([3, 3])


In [46]:
t=torch.torch.rand(3,3)
print(t)
print(t.shape)

tensor([[0.0995, 0.8647, 0.9609],
        [0.4372, 0.7036, 0.1368],
        [0.8356, 0.7942, 0.1638]])
torch.Size([3, 3])


In [47]:
tensor=t.unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[[0.0995, 0.8647, 0.9609],
         [0.4372, 0.7036, 0.1368],
         [0.8356, 0.7942, 0.1638]]])
torch.Size([1, 3, 3])


In [48]:
tensor=t.unsqueeze(dim=2)
print(tensor)
print(tensor.shape)

tensor([[[0.0995],
         [0.8647],
         [0.9609]],

        [[0.4372],
         [0.7036],
         [0.1368]],

        [[0.8356],
         [0.7942],
         [0.1638]]])
torch.Size([3, 3, 1])


In [50]:
x=torch.FloatTensor([1,4])
print(x)
y=torch.FloatTensor([2,5])
print(y)
z=torch.FloatTensor([3,6])
print(z)

print(torch.stack([x,y,z]))

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
